# <center>Practical 15</center>

### WAP to return the highest and lowest values in the list

In [2]:
print("chaudhary kanishk")

import random

nums = [random.randint(1, 100) for _ in range(10)]
print("nums :", nums)
print("max :", max(nums))
print("min :", min(nums))


chaudhary kanishk
nums : [47, 76, 47, 38, 22, 35, 6, 52, 95, 46]
max : 95
min : 6


### WAP to swap two values using tuple assignment.

In [3]:
print("chaudhary kanishk")

def swap_values(a, b):
    print("Before swapping:")
    print("a =", a)
    print("b =", b)

    a, b = b, a

    print("After swapping:")
    print("a =", a)
    print("b =", b)

swap_values(5, 10)

chaudhary kanishk
Before swapping:
a = 5
b = 10
After swapping:
a = 10
b = 5


### WAP using a function that returns the area and circumference of a circle whose radius is passed as an argument.

In [4]:
print("chaudhary kanishk")
import math

def calculate_area_and_circumference(radius):
    area = math.pi * radius**2
    circumference = 2 * math.pi * radius    
    return area, circumference

def main():
    radius = float(input("radius : "))
    print("radius :", radius)
    area, circumference = calculate_area_and_circumference(radius)
    print("Area:", area)
    print("Circumference:", circumference)

if __name__ == "__main__":
    main()

chaudhary kanishk
radius : 4.0
Area: 50.26548245743669
Circumference: 25.132741228718345


### WAP using filter() function to a list of cubes of numbers from 1 – 10.

In [5]:
print("chaudhary kanishk")

def is_cube(num):
    cube_root = round(num ** (1/3))
    return cube_root ** 3 == num

numbers = [i**3 for i in range(1, 10)]

cubes_filter = filter(is_cube, numbers)

cubes_list = list(cubes_filter)
print(cubes_list)


chaudhary kanishk
[1, 8, 27, 64, 125, 216, 343, 512, 729]


### WAP that reverse a list using a loop

In [6]:
print("chaudhary kanishk")

def reverse_list(lst):
    length = len(lst)
    for i in range(length // 2):
        # Swap elements from the beginning and end
        lst[i], lst[length - i - 1] = lst[length - i - 1], lst[i]

my_list = [1, 2, 3, 4, 5]
print("Original list:", my_list)
reverse_list(my_list)
print("Reversed list:", my_list)

chaudhary kanishk
Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


### WAP to find whether a particular element is present in the list using a loop.

In [7]:
print("chaudhary kanishk")

my_list = [1, 2, 3, 4, 5]
target_element = 3

if target_element in my_list:
    print(f"{target_element} is present in the list.")
else:
    print(f"{target_element} is not present in the list.")


chaudhary kanishk
3 is present in the list.


### WAP that prints all consonants in a string using list comprehension.

In [8]:
print("chaudhary kanishk")

def is_consonant(char):
    return char not in "AEIOUaeiou"
input_string = "Hello World"
consonants = [char for char in input_string if is_consonant(char)]
print("Consonants in the string:", ''.join(consonants))

chaudhary kanishk
Consonants in the string: Hll Wrld


### WAP that counts the number of times a value appears in the list. Use a loop to do the same.

In [9]:
print("chaudhary kanishk")
def count_occurrences(lst, value):
    count = 0
    for item in lst:
        if item == value:
            count += 1
    return count

my_list = [1, 2, 3, 4, 2, 2, 5, 2]
target_value = 2
occurrences = count_occurrences(my_list, target_value)
print(f"The value {target_value} appears {occurrences} times in the list.")

chaudhary kanishk
The value 2 appears 4 times in the list.


### WAP to insert a value in the list at the specified location using while loop.

In [10]:
print("chaudahry kanishk")
def insert_value_at_location(lst, value, location):
    index = 0
    while index < len(lst):
        if index == location:
            lst.insert(location, value)
            break
        index += 1
    else:
        lst.append(value)

my_list = [1, 2, 3, 4, 5]
insert_value_at_location(my_list, 10, 2)
print("Updated list:", my_list)

chaudahry kanishk
Updated list: [1, 2, 10, 3, 4, 5]


### WAP to transpose two matrices.

In [11]:
print("chaudhary kanishk")
import numpy as np

matrix1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
matrix2 = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])
transposed_matrix1 = np.transpose(matrix1)
transposed_matrix2 = np.transpose(matrix2)
print("Transposed Matrix 1:")
print(transposed_matrix1)
print("\nTransposed Matrix 2:")
print(transposed_matrix2)

chaudhary kanishk


Transposed Matrix 1:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Transposed Matrix 2:
[[9 6 3]
 [8 5 2]
 [7 4 1]]
