# <center>Practical 20</center>

### 1. Write a NumPy program to create a 3X4 array and iterate over it.

In [1]:
print("Kanishk Chaudhari")
import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
for row in array:
    for element in row:
        print(element, end=" ")
    print()

Kanishk Chaudhari
1 2 3 4 
5 6 7 8 
9 10 11 12 


### 2. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [2]:
print("Kanishk Chaudhari")
import numpy as np
matrix = np.arange(10, 22).reshape(3, 4)
print(matrix)

Kanishk Chaudhari
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


### 3. Write a NumPy program to create a 10 * 10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [3]:
print("Kanishk Chaudhari")
import numpy as np
matrix = np.zeros((10, 10))
matrix[0]= 1
matrix[-1: ] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1
print(matrix)

Kanishk Chaudhari
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 4. Write a Python function that takes two 2D arrays as input and returns their matrix product using NumPy.

In [4]:
print("Kanishk Chaudhari")
import numpy as np
array1 = np.array([[1, 2],
                   [3, 4]])
array2 = np.array([[5, 6],
                   [7, 8]])
result = np.dot(array1, array2)
print("Matrix Product:")
print(result)

Kanishk Chaudhari
Matrix Product:
[[19 22]
 [43 50]]


### 5. Write a Python function that takes a 1D NumPy array as input and returns a new array with all even numbers squared and odd numbers unchanged.

In [5]:
print("Kanishk Chaudhari")
import numpy as np
array = np.array([1, 2, 3, 4, 5])
array[array%2 == 0] **= 2
print(array)

Kanishk Chaudhari
[ 1  4  3 16  5]


### 6. Write a NumPy program to compute the sum of all elements, the sum of each column and the sum of each row in a given array.

In [6]:
print("Kanishk Chaudhari")
import numpy as np
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
total_sum = np.sum(array)
column_sums = np.sum(array, axis=0)
row_sums = np.sum(array, axis=1)
print("Sum of All Elements:", total_sum)
print("Sum of Each Column:", column_sums)
print("Sum of Each Row:", row_sums)

Kanishk Chaudhari
Sum of All Elements: 45
Sum of Each Column: [12 15 18]
Sum of Each Row: [ 6 15 24]


### 7. Write a NumPy program to add a vector to each row of a given matrix.

In [7]:
print("Kanishk Chaudhari")
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
vector = np.array([10, 11, 12])
result = matrix + vector 
print("Resultant Matrix:")
print(result)

Kanishk Chaudhari
Resultant Matrix:
[[11 13 15]
 [14 16 18]
 [17 19 21]]


### 8. Consider a given series:
<pre>
QTR1 50000
QTR2 65898
QTR3 56780
QTR4 89000
QTRS 77900
Write a program in Python Pandas to create and display the series.
</pre>

In [8]:
print("Kanishk Chaudhari")
import pandas as pd
data = {
    "QTR1" : 50000,
    "QTR2" : 65898,
    "QTR3" : 56780,
    "QTR4" : 89000,
    "QTRS" : 77900
}

series = pd.Series(data)
print("Given Series:")
print(series)

Kanishk Chaudhari
Given Series:
QTR1    50000
QTR2    65898
QTR3    56780
QTR4    89000
QTRS    77900
dtype: int64
